docs: Renamed 'DependableTrait' to new name 'Dependable'
aws/constructs pull request #1087
Opened 2022-06-02 14:45 UTC by ThomasSteinbach

It looks like the former Name of 'Dependable' was 'DependableTrait'. Latter name is mentioned in the code documentation, which doesn't fit to the code anymore. I updated the docs regarding the current code.

2022-06-06 16:04 UTC, Chriscbr requested changes

2022-06-06 16:04 UTC, Chriscbr commented on src/dependency.ts
> + * an `Dependable` implementation.
I believe this should be
```suggestion
 * an `IDependable` implementation.
```

2022-06-14 08:19 UTC, ThomasSteinbach commented
@Chriscbr thank you for your review and change suggestion. I have applied your suggestion and updated the `API.md` file.
Could you please review again.
Thanks - Thomas

2022-06-14 19:49 UTC, Chriscbr approved these changes

2022-06-14 19:53 UTC, merged